# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
    tags: ['*']

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          needs: website

      # `Amelia` is not available on R<4.0.0 because of `foreign` import.
      # It is only only used on the website; and not on a CRAN vignette.
      - name: Amelia
        run: Rscript -e "try(install.packages('Amelia'))"

      - name: MCMCglmm
        run: Rscript -e "try(install.packages('MCMCglmmm'))"

      - name: wesanderson
        run: Rscript -e "try(install.packages('wesanderson'))"

      - name: modelr
        run: Rscript -e "try(install.packages('modelr'))"

      - name: tidyverse
        run: Rscript -e "try(install.packages('tidyverse'))"

      - name: ggdist
        run: Rscript -e "try(install.packages('ggdist'))"

      - name: tictoc
        run: Rscript -e "try(install.packages('tictoc'))"

      - name: Deploy package
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
